services:
  server:
    image: csang/htecho:latest
    build:
      context: .
      dockerfile: ./build/prod/Dockerfile
    command: ["--addr=0.0.0.0:8080"]
    ports:
      - "8080:8080"

  dev:
    image: csang/htecho-dev:latest
    build:
      context: .
      dockerfile: ./build/dev/Dockerfile

  test:
    extends:
      service: dev
    command: ["go", "test", "-v", "./..."]

  cover:
    extends:
      service: dev
    command: ["/bin/sh", "-c", "go test -coverprofile=c.out './...' && go tool cover -func=c.out"]
